import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Todo List",
    description: "Generated by Mohammad Shahheydar",
};

/**
 * @description app root
 * @param children
 */
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/*navbar*/}
                <main>
                    <div className="layout">
                        <StoreProvider>
                            {children}
                        </StoreProvider>
                    </div>
                </main>
                {/*footer*/}
            </body>
        </html>
    );
}
